### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by yjq404** [ShuvenduRoy/ActiveFER#1]
Thank you for the open source, I am following the steps to reproduce your code using the FER13 dataset and it shows the following error:
    UnboundLocalError: local variable 'train_dataset' referenced before assignment
Then I modified the following part：
    if opt.dataset == 'FER13':
        dir = './data/FER13'
        train_dataset = AffectDataset(dir, train=True, download=True, transform=TwoCropTransform(train_transform))
But it still reports the following error:
   FileNotFoundError: [Errno 2] No such file or directory: './data/FER13/train_data.npy'
Do you know why? Looking forward to your reply, thanks!

**Comment by dsxieweizhi** [comment]
> Thank you for the open source, I am following the steps to reproduce your code using the FER13 dataset and it shows the following error: UnboundLocalError: local variable 'train_dataset' referenced before assignment Then I modified the following part： if opt.dataset == 'FER13': dir = './data/FER13' train_dataset = AffectDataset(dir, train=True, download=True, transform=TwoCropTransform(train_transform)) But it still reports the following error: FileNotFoundError: [Errno 2] No such file or directory: './data/FER13/train_data.npy' Do you know why? Looking forward to your reply, thanks!

 me too

**Comment by 123duduke** [comment]
请问你们问题解决了吗

**Comment by ghost** [comment]
> Thank you for the open source, I am following the steps to reproduce your code using the FER13 dataset and it shows the following error: UnboundLocalError: local variable 'train_dataset' referenced before assignment Then I modified the following part： if opt.dataset == 'FER13': dir = './data/FER13' train_dataset = AffectDataset(dir, train=True, download=True, transform=TwoCropTransform(train_transform)) But it still reports the following error: FileNotFoundError: [Errno 2] No such file or directory: './data/FER13/train_data.npy' Do you know why? Looking forward to your reply, thanks!

Have you solved your problem

**Comment by ShuvenduRoy** [comment]
This was caused by the fact that we saved the dataset as a .npy object for quick loading. It was optimal because of the small size of the datasets. 

I have updated the code to directly load from the dataset. Please download the datasets from official websites and organize them as directed in the readme.
